flowchart LR
A{Aerospace Engineer}-->|has RDF type|B{Job Classification}
A-->|Has OWN Code|C[1235]
A-->|HAS OCC Code|D[17-2010]
A-->|Has quality|[Engineer]
D-->|Has O Group|G[broad]
D-->|Has Area|J[99]
D-->|Has estimated Total Employment|K[68440]

A-->|HAS OCC Code|E[17-2011]
E-->|Has O Group|H[detailed]
E-->|Has Area|K[99]
E-->|Has estimated Total Employment|M[68440]

A-->|HAS OCC Code|F[17-3021]
F-->|Has O Group|I[detailed]
F-->|Has Area|L[99]
F-->|Has estimated Total Employment|N[9060]

O[Occupational Employment and Wage Statistics]-->|Inheres in Act of Measuring|A